name: Tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: ./
    concurrency:
      group: npm-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: 'package/yarn.lock'

      - name: Install dependencies
        working-directory: package
        run: yarn

      - name: TypeScript
        working-directory: package
        run: yarn tsc

      - name: Lint
        working-directory: package
        run: yarn lint

      - name: Build
        working-directory: package
        run: yarn build

      - name: Tests
        working-directory: package
        run: |
          sudo apt-get install -y xvfb
          xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' yarn test

      - name: Install dependencies
        working-directory: example
        run: yarn

      - name: TypeScript
        working-directory: example
        run: yarn tsc

      - name: Lint
        working-directory: example
        run: yarn lint